In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
#Read in IBB Index.csv as pandas dataframe
df = pd.read_csv('IBB Index.csv')

In [30]:
type(df)

pandas.core.frame.DataFrame

In [14]:
df.shape

(261, 2)

In [20]:
from torch.utils.data import TensorDataset, DataLoader

In [31]:
Open = df.drop('Date', axis=1).values

In [33]:
IBB = TensorDataset(torch.FloatTensor(Open))

In [35]:
IBB

In [37]:
for i in IBB:
    print(i)

(tensor([35.1767]),)
(tensor([36.1400]),)
(tensor([37.9000]),)
(tensor([37.8600]),)
(tensor([38.5367]),)
(tensor([40.1133]),)
(tensor([40.0867]),)
(tensor([39.7167]),)
(tensor([39.7333]),)
(tensor([39.9533]),)
(tensor([39.9133]),)
(tensor([40.1867]),)
(tensor([40.7867]),)
(tensor([41.2067]),)
(tensor([40.6567]),)
(tensor([39.4600]),)
(tensor([40.4800]),)
(tensor([42.2167]),)
(tensor([40.7133]),)
(tensor([41.9767]),)
(tensor([40.2500]),)
(tensor([41.6667]),)
(tensor([39.8233]),)
(tensor([41.6267]),)
(tensor([41.5667]),)
(tensor([42.5200]),)
(tensor([43.4700]),)
(tensor([44.1200]),)
(tensor([44.0800]),)
(tensor([43.8267]),)
(tensor([45.8633]),)
(tensor([44.3833]),)
(tensor([44.1100]),)
(tensor([44.3367]),)
(tensor([45.4633]),)
(tensor([45.5800]),)
(tensor([46.9367]),)
(tensor([47.2133]),)
(tensor([47.9533]),)
(tensor([47.7333]),)
(tensor([49.0600]),)
(tensor([47.3333]),)
(tensor([46.4833]),)
(tensor([44.9000]),)
(tensor([43.7333]),)
(tensor([44.]),)
(tensor([44.4600]),)
(tensor([46.0467]